### PR TITLE
updated navbar with color and logo

### PR DESCRIPTION
**Pull request by ChucklesOnGitHub**
We were discussing with @cjsha. This PR would maintain style across OE docs, instead of using the Miniscope team logo.

The target of these docs seem to be for the acquisition system "Miniscope DAQ" and the OpenEphys.Miniscope library, which at the moment include UCLA Miniscope v3, UCLA Miniscope v4 and MiniCAM. This is work that stems from the UCLA Miniscopes but encompasses the OE take on this ecosystem. Note these docs do not include guides on working with the Miniscope-DAQ-qt software because it is deprecated and not able to be supported by our dev team. These docs also don't include Miniscope usage in ONIX, so we decided against calling them Miniscopes.

re: the discussion https://github.com/open-ephys/miniscope-docs/issues/24 I don't understand if this DAQ with also aquire from kiloscope eventually.
I also don't know what the new DAQ OEPS is working on will be called, but I expect usage would be included in these docs.

NB: I changed the navbar color values from the template due to contrast issues, I copied the colors from the last docs created (commutator): https://github.com/open-ephys/commutator-docs/blob/main/source/_static/theme_overrides.css

### CODE REVIEW

**Comment by jonnew** [comment]
The DAQ will indeed acquire for kiloscope. Can you simply share a screen shot of what this looks like so I can have a look without building?

**Comment by sneakers-the-rat** [comment]
yipes just went to check out the issues in this repo and i think it might be time to chat soon about miniscope software :) - i'm back to working on this regularly as of this week, need to do a bit of (a lot of) refactoring after we basically smashed two packages together, but target for me is to port the qt-daq code to a C-extension in december. i'm gonna make a neat lil python/rust device graph system and would love to know if ya wanna collaborate on either end of us supporting your devices or us making our software available to your systems. have been chipping away at making a uniform declarative API so that we can also expose to bonsai in a relatively low maintenance way too, bc formerly we were not rly helping with API stability and i'm trying to change that for some of the new devices coming out.

> Can you simply share a screen shot of what this looks like so I can have a look without building?

side note, i see this is sphinx already, i have been sold on the divine light of docs previews in PRs and we added them to miniscope-io last week and it's super easy and also the best: https://github.com/Aharoni-Lab/miniscope-io/pull/53

github has sort of been [dragging their feet since 2021](https://github.com/orgs/community/discussions/7730) on this, but it works well with readthedocs :)

**Comment by ChucklesOnGitHub** [comment]
> Can you simply share a screen shot of what this looks like so I can have a look without building?
image

The highlighting mimicks this one:
image

I don't care specifically for the color pink, I was just trying to continue our rainbow:
image

**Comment by jonnew** [comment]
> yipes just went to check out the issues in this repo and i think it might be time to chat soon about miniscope software :) - i'm back to working on this regularly as of this week, need to do a bit of (a lot of) refactoring after we basically smashed two packages together, but target for me is to port the qt-daq code to a C-extension in december. i'm gonna make a neat lil python/rust device graph system and would love to know if ya wanna collaborate on either end of us supporting your devices or us making our software available to your systems. have been chipping away at making a uniform declarative API so that we can also expose to bonsai in a relatively low maintenance way too, bc formerly we were not rly helping with API stability and i'm trying to change that for some of the new devices coming out.
> 
> > Can you simply share a screen shot of what this looks like so I can have a look without building?
> 
> side note, i see this is sphinx already, i have been sold on the divine light of docs previews in PRs and we added them to miniscope-io last week and it's super easy and also the best: [Aharoni-Lab/miniscope-io#53](https://github.com/Aharoni-Lab/miniscope-io/pull/53)
> 
> github has sort of been [dragging their feet since 2021](https://github.com/orgs/community/discussions/7730) on this, but it works well with readthedocs :)

Wow! Thats awesome. @bparks13 when you have a moment can you look at what Jonny did here. I think the most relevant thing is this: https://github.com/Aharoni-Lab/miniscope-io/pull/53/files. It would be very nice for us to copy their their automated preview in these docs discussions. 

Also, @sneakers-the-rat very neat work on the miniscope-io stuff. We have a lot of users that would prefer an alternative to bonsai, so Im glad there might be a different option for them.

**Review by jonnew — CHANGES_REQUESTED** [review]
Looks great, but I would replace "Miniscope DAQ" with "Miniscopes"

**Comment by ChucklesOnGitHub** [comment]
> Looks great, but I would replace "Miniscope DAQ" with "Miniscopes"

@jonnew we didn't call it Miniscopes only because we are going to include the MiniCAM in here and because ONIX also acquires from Miniscopes. DAQ is unfortunately in the name of the product https://open-ephys.org/miniscope-daqs/daq.
I'm not sure if you had seen that part of the rationale. Just lmk.

**Review by cjsha — APPROVED** [review]
looks good

**Comment by ChucklesOnGitHub** [comment]
@jonnew could you review and accept this please? I made the change you asked for (the logo now says Miniscopes only). The "Change requested" review blocked the ability to merge this without you reviewing it again.
I want to advertise these docs but they really have to conform to our style for them to be easily identifiable as Open Ephys docs.

**Pull request closed without merging**
